### ISSUE TITLE
SNSP-CPU-02

### ISSUE THREAD

**Issue by danxster** [marqs85/snes_dejitter#4]
I have a SNSP-CPU-02, I can't seem to find the solder points for this model. 

Could someone please help out, I have a snes_dejitter 1.3?

![img_2331](https://user-images.githubusercontent.com/6374626/46796883-073a1880-cd91-11e8-8abf-1b9cc95cb1be.jpg)
![img_2332](https://user-images.githubusercontent.com/6374626/46796884-073a1880-cd91-11e8-8740-b3f53e8600ae.jpg)

**Comment by marqs85** [comment]
Looking at [this](https://console5.com/wiki/File:PAL-SNES_Schematic.pdf) schematic, you'd need to first desolder R73 and either R33 (sync on CVBS) or R25 (sync on luma) depending on the RGB cable you use. After that:

-CSYNC_i is connected to S-ENC pin 8
-CSYNC_o is connected to multiAV side of removed R33 / R25
-MCLK_o is connected to CPU side of removed R73
-5V and GND are connected to nearest place where you can get them easily

Since you seem to have region mod in place, you might want to keep PAL mode as close to 50Hz as possible (which would otherwise be slightly off with NTSC MCLK). For that you'll need to additionally connect S-CLK side of R73 to MCLK_EXT_i and PAL selection pin (same that goes to S-PPU1 pin 24) to MCLK_SEL_i.

**Comment by danxster** [comment]
I use a sync on Luma cable. 

@marqs85 - Is this correct?

![pic 1](https://user-images.githubusercontent.com/6374626/46901729-ffe34e00-cefb-11e8-83ad-eb8f41323721.jpg)
![pic 2](https://user-images.githubusercontent.com/6374626/46901730-01ad1180-cefc-11e8-936c-575a95eeeb49.jpg)

**Comment by marqs85** [comment]
That looks ok, but I'd rotate the mod board by 180deg and move it left so that length of MCLK_o wire can be kept minimum. Now that I re-checked the schematic, CSYNC_o actually should be directly connected to multiAV pin7 (R25 must be still removed).

**Comment by danxster** [comment]
I'm not getting any picture with the following configuration, any ideas?

![img_2370](https://user-images.githubusercontent.com/6374626/47643077-194fef80-dbb6-11e8-81d5-774816bc8eca.jpg)
![img_2371](https://user-images.githubusercontent.com/6374626/47643082-1b19b300-dbb6-11e8-99e4-e179467442d3.jpg)

**Comment by marqs85** [comment]
On the upper pic, it seems you've hooked 5V and GND to C9 which is not a supply rail cap if you check the schematic. C92 should be good for that and is also closer. On the bottom pic, it looks you may have connected to pin 99 of PPU2 instead of 100 but the resolution is not high enough to say for sure. Similarly, pin 29 and 30 look shorted.

**Comment by danxster** [comment]
Thanks for your help, its now function perfectly :-)

This is what I did to get it working:
5V and GND to C92
Connected to PPU2 on pin 100

**Comment by marqs85** [comment]
Good to hear that. I noticed you've not connected CLK_SEL_i pin of the board which is OK in case you're fine with slightly off-50Hz refresh rate in PAL mode. If you connect it as described in my first reply, you'll get accurate 50Hz but in that case you shouldn't do 50/60 switching while running a game as clock muxing is not glitchless. Could you also take photos of completed installation so that I can create instructions for SNSP-CPU-02?

**Comment by marqs85** [comment]
Added instructions for SNSP-CPU-02 based on this. Closing the issue.
